#!/usr/bin/env bash
#script to check if a file exists

file_path="/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school"
if [ -e "$file_path" ]; then
    echo "school file exists"
    if [ ! -s "$file_path" ]; then
        echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    if [ -f "$file_path" ]; then
	echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi
